/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

var cities = ["Taipei City", "New Taipei City", "Taichung City", "Tainan City", "Kaohsiung City", "Keelung City", "Taoyuan City", "Hsinchu City", "Hsinchu County", "Miaoli County", "Changhua County", "Nantou County", "Yunlin County", "Chiayi City", "Chiayi County", "Pingtung County", "Yilan County", "Hualien County", "Taitung County", "Penghu County", "Kinmen County", "Matsu"];
var cityIDs = [2306179, 20070569, 2306181, 2306182, 2306180, 2306188, 2298866, 2306185, 56027303, 2301128, 2306183, 2306204, 2347346, 2296315, 56793485, 2306189, 2306198, 2306187, 2306190, 56810980, 90413525, 90413693];



function createList() {
  for (i = 0; i < cities.length; i++) {
    $('#dropdown').append("<li role='presentation'><a role='menuitem' tabindex='"+i+"' href='#'>" + cities[i] + "&nbsp&nbsp<span></span></a></li>");
  }
  skycons.play();

}
createList();


$tempers = $('#dropdown li span');
$tempers.each(function(index, element) {

    var $thisTemp = $(this);
    getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + cities[index] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
    function(data) {
      var temp = data.query.results.channel.item.condition.temp;
      temp = parseInt((parseInt(temp) - 32) * 5 / 9);

      $thisTemp.html(temp+"&#8451;");
    })
})



$('#dropdown li').on('click', function() {
  today($(this).find('a').attr('tabindex'))
  forecast($(this).find('a').attr('tabindex'))
  var skycons = new Skycons();

  skycons.play();

})

function today(i) {
  getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + cities[i] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
 function(data) {
    // 可以比較方便找到你要的資料在這個物件的哪個位置
    var date = data.query.results.channel.item.condition.date;
    var temp = data.query.results.channel.item.condition.temp;
    var code = data.query.results.channel.item.condition.code;
    code = parseInt(code);

    $(".condition .date").text(date);
    $("#todayTemp").text(parseInt((parseInt(temp) - 32) * 5 / 9));
    icon("today", code);
    $("#selected").text(cities[i]);


  })
};
today(0);

function forecast(i) {
  getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20item.forecast%20from%20weather.forecast%20where%20woeid%20%3D%20"+cityIDs[i]+"&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
function(data) {
    console.log(data.query.results.channel[0].item);
    for (j = 1; j < 4; j++) {
      var date = data.query.results.channel[j].item.forecast.date;
      var high = data.query.results.channel[j].item.forecast.high;
      var low = data.query.results.channel[j].item.forecast.low;
      var code = data.query.results.channel[j].item.forecast.code;
      code = parseInt(code);

      $("#day" + j + "date").text(date);
      $("#day" + j + "temp").html(parseInt((parseInt(low) - 32) * 5 / 9) + "-" + parseInt((parseInt(high) - 32) * 5 / 9) + "&#8451;");
      icon("day" + j + "text", code);


    }
  })
};
forecast(0);

function getJsonUntilSuccess(url, callback) {
  $.getJSON(url, function(data) {
    if (data.query.results) { // if data.query.results exist , do the following action.
      callback(data);
    } else {
      // console.info("reloading : ", url);
      getJsonUntilSuccess(url, callback);
    }
  })
}

var icon = function(id, code) {
  switch (code) {
    case 32:
    case 34:
    case 36:
      skycons.set(id, Skycons.CLEAR_DAY);
      break;
    case 31:
    case 33:
      skycons.set(id, Skycons.CLEAR_NIGHT);
      break;
    case 30:
    case 44:
      skycons.set(id, Skycons.PARTLY_CLOUDY_DAY);
      break;
    case 29:
      skycons.set(id, Skycons.PARTLY_CLOUDY_NIGHT);
      break;
    case 27:
    case 28:
      skycons.set(id, Skycons.CLOUDY);
      break;
    case 3:
    case 4:
    case 11:
    case 12:
    case 39:
      skycons.set(id, Skycons.RAIN);
      break;
    case 18:
      skycons.set(id, Skycons.SLEET);
      break;
    case 16:
      skycons.set(id, Skycons.SNOW);
      break;
    case 24:
      skycons.set(id, Skycons.WIND);
      break;
    case 20:
      skycons.set(id, Skycons.FOG);
      break;

    default:
      break;
  }
}
